import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { buildProject } from "../scripts/build-appscript.mjs";

test("el build genera Apps Script y GitHub Pages", async () => {
  const result = await buildProject();
  assert.deepEqual(result.htmlFiles, ["Index.html", "IndexOperator.html", "IndexSkills.html", "Bridge.html"]);
  assert.deepEqual(result.pagesFiles, ["index.html", "operator.html", "skills.html", "manifest.webmanifest", "sw.js"]);
  const index = await readFile(path.join(result.distDir, "Index.html"), "utf8");
  const performanceService = await readFile(path.join(result.distDir, "15-performance-service.js"), "utf8");
  const storageService = await readFile(path.join(result.distDir, "02-storage.js"), "utf8");
  const codeService = await readFile(path.join(result.distDir, "01-code.js"), "utf8");
  const bridge = await readFile(path.join(result.distDir, "Bridge.html"), "utf8");
  assert.match(index, /<title>Planeacion de Produccion<\/title>/);
  assert.match(index, /google\.script\.run/);
  assert.match(index, /PPAppsScriptBridge/);
  assert.match(index, /getAppState/);
  assert.match(index, /savePlanningStateOptimized/);
  const pagesIndex = await readFile(path.join(result.siteDir, "index.html"), "utf8");
  const serviceWorker = await readFile(path.join(result.siteDir, "sw.js"), "utf8");
  assert.match(serviceWorker, /const CACHE_NAME = "plan-maestro-[a-f0-9]{12}";/);
  assert.doesNotMatch(serviceWorker, /plan-maestro-v2\.41\.4/);
  assert.match(pagesIndex, /script\.google\.com\/macros\/s\//);
  assert.match(pagesIndex, /manifest\.webmanifest/);
  assert.match(pagesIndex, /serviceWorker\.register/);
  assert.match(pagesIndex, /PlannerCore/);
  assert.match(pagesIndex, /PlanningWorkflowCore/);
  assert.match(pagesIndex, /PlanningWorkflowCore\.weeklyFinishingCost\(finishingRows\)/);
  assert.match(pagesIndex, /formatCurrency\(window\.PlanningWorkflowCore\.effectiveFinishingAmount\(row\)\)/);
  assert.match(pagesIndex, /return window\.PlanningWorkflowCore\.weeklyFinishingRowsByType\(rows\);/);
  assert.match(pagesIndex, /const finishingRows = summary\.finishes \|\| \[\];/);
  assert.doesNotMatch(pagesIndex, /const startingRows = summary\.starts \|\| \[\];/);
  assert.doesNotMatch(pagesIndex, /Number\(row\.amount \|\| 0\)/);
  assert.match(pagesIndex, /Number\.isFinite\(amountNumber\)/);
  assert.match(pagesIndex, /Number\.isFinite\(unitPriceNumber\)/);
  assert.match(pagesIndex, /Number\.isFinite\(pendingPiecesValue\)/);
  assert.match(pagesIndex, /window\.PlanningWorkflowCore = api/);
  assert.doesNotMatch(pagesIndex, /const window = getPlanWindow\(\);[\s\S]{0,1800}window\.PlanningWorkflowCore\.isActiveGanttView/);
  assert.doesNotMatch(pagesIndex, /createPlanningWorkflowCore[\s\S]*?<\/script>\s*<script>\s*"use strict";\s*const STORAGE_KEY/);
  assert.match(pagesIndex, /scheduleCurrentPlan/);
  assert.match(pagesIndex, /NETSUITE_PLANNING_TIMEOUT_MS = 15000/);
  assert.match(pagesIndex, /PlanningWorkflowCore\.withTimeout/);
  assert.match(pagesIndex, /const removal = window\.PlanningWorkflowCore\.canRemoveSelectedOt\(state, ot\);[\s\S]{0,180}if \(!removal\.allowed\)[\s\S]{0,180}showToast\(removal\.reason\)[\s\S]{0,1200}PlanningWorkflowCore\.removeOtFromDraft/);
  assert.match(pagesIndex, /prepareDraftForReschedule/);
  assert.match(pagesIndex, /const originalSelectedOts = \[\.\.\.state\.selectedOts\];[\s\S]{0,900}PlannerCore\.schedulePlan\(\{ \.\.\.state, selectedOts: readyOts \}, \{/);
  assert.match(pagesIndex, /state = \{ \.\.\.result, selectedOts: originalSelectedOts \};/);
  assert.match(pagesIndex, /NetSuite no respondio; se programara con los datos ya cargados/);
  assert.match(pagesIndex, /originalEnsurePlanningDataLoaded\(showMessage, options\)/);
  assert.match(pagesIndex, /return \{ ready: hasData\(\), source: "fresh", warning: "" \}/);
  assert.match(pagesIndex, /netSuiteSyncOutcome/);
  assert.match(pagesIndex, /subcontractWindowEnd/);
  assert.match(pagesIndex, /name="ot_manual_price" type="number" min="0"/);
  assert.doesNotMatch(pagesIndex, /Piezas pendientes/);
  assert.doesNotMatch(pagesIndex, /Monto estimado/);
  assert.match(pagesIndex, /configuration\.subcontractType \|\| registeredSubcontract/);
  assert.match(pagesIndex, /configuration\.machine/);
  assert.match(pagesIndex, /function setPlanningActionsBusy/);
  assert.match(pagesIndex, /setPlanningActionsBusy\("schedule", true\)/);
  assert.match(pagesIndex, /setPlanningActionsBusy\("sync", true\)/);
  assert.match(pagesIndex, /id="syncBacklogOtsBtn"[^>]*>Sincronizar OTs<\/button>/);
  assert.match(pagesIndex, /async function syncBacklogWorkOrders\(\)/);
  assert.match(pagesIndex, /PlanningWorkflowCore\.compareWorkOrderLite\(state, incomingWorkOrders\)/);
  assert.match(pagesIndex, /PlanningWorkflowCore\.applyConfirmedWorkOrderChanges\(state, comparison, decisions\)/);
  assert.match(pagesIndex, /setPlanningActionsBusy\("backlog-sync", true\)/);
  assert.match(pagesIndex, /setPlanningActionsBusy\("backlog-sync", false\)/);
  assert.match(pagesIndex, /id="restoreDraftBtn"[^>]*>Restaurar borrador<\/button>/);
  assert.equal((pagesIndex.match(/id="restoreDraftBtn"/g) || []).length, 1);
  assert.match(pagesIndex, /async function openRestoreDraftDialog\(\)/);
  assert.match(pagesIndex, /async function previewDraftRestore\(snapshotId, syncBeforeRestore\)/);
  assert.match(pagesIndex, /async function confirmDraftRestore\(snapshotId\)/);
  assert.match(pagesIndex, /PlanningWorkflowCore\.reconcilePublishedPlan\(snapshot, state\)/);
  assert.match(pagesIndex, /restoredOts[\s\S]*closedOts[\s\S]*completedOperations[\s\S]*removedOperations[\s\S]*newOperations[\s\S]*preservedConfigurations/);
  assert.match(pagesIndex, /Sincronizar antes de restaurar/);
  assert.match(pagesIndex, /Continuar con datos cargados/);
  assert.match(pagesIndex, /reemplaza el borrador[\s\S]*conserva un respaldo[\s\S]*publicado permanece intacto/i);
  assert.match(pagesIndex, /setPlanningActionsBusy\("restore", true\)/);
  assert.match(pagesIndex, /setPlanningActionsBusy\("restore", false\)/);
  assert.match(pagesIndex, /callAppsScript\("restorePublishedPlanAsDraft", snapshotId, createAppSheetPayload\(\)\)/);
  assert.match(pagesIndex, /reportSnapshot = null;[\s\S]*Borrador restaurado; revisa y genera nuevamente el plan/);
  const restoreOpenSource = pagesIndex.slice(pagesIndex.indexOf("async function openRestoreDraftDialog()"), pagesIndex.indexOf("async function previewDraftRestore("));
  const restorePreviewSource = pagesIndex.slice(pagesIndex.indexOf("async function previewDraftRestore("), pagesIndex.indexOf("async function confirmDraftRestore("));
  const restoreConfirmSource = pagesIndex.slice(pagesIndex.indexOf("async function confirmDraftRestore("), pagesIndex.indexOf("async function loadPlanSnapshots("));
  [restoreOpenSource, restorePreviewSource, restoreConfirmSource].forEach((source) => {
    assert.match(source, /netSuiteSyncInFlight \|\| netSuitePlanningSyncInFlight/);
  });
  assert.match(pagesIndex, /function setNetSuiteSyncState\(inProgress\)[\s\S]*restoreDraftBtn\.disabled = inProgress \|\| Boolean\(planningActionsBusy\)/);
  assert.ok(restoreConfirmSource.indexOf("await loadPlanSnapshots(false)") < restoreConfirmSource.indexOf("reportSnapshot = null"));
  assert.match(restoreConfirmSource, /showWorkspaceView\("plan-semanal"\)/);
  assert.match(pagesIndex, /Cantidad diferente en NetSuite/);
  assert.match(pagesIndex, /Cerrada o no encontrada en NetSuite/);
  const backlogSyncSource = pagesIndex.slice(
    pagesIndex.indexOf("async function syncBacklogWorkOrders()"),
    pagesIndex.indexOf("async function syncNetSuiteTwoPhase()"),
  );
  assert.match(backlogSyncSource, /callAppsScript\("syncNetSuiteWorkOrdersLite"\)/);
  assert.doesNotMatch(backlogSyncSource, /syncNetSuitePlanningData|syncNetSuitePlant|syncNetSuiteWorkOrders"/);
  assert.doesNotMatch(pagesIndex, /id="balanceBtn"/);
  assert.doesNotMatch(pagesIndex, /els\.balanceBtn\.addEventListener/);
  assert.match(pagesIndex, /if \(isSubcontractAppOperation\(op\)\) requirement\.codes\.add\("OT_SUBCONTRACT"\)/);
  assert.match(pagesIndex, /if \(window\.PlannerCore\?\.isBendingOperation\?\.\(op\)\)[\s\S]*requirement\.codes\.add\("OT_TOOL"\)[\s\S]*requirement\.codes\.add\("OPTIONAL_KIT"\)/);
  assert.match(pagesIndex, /const result = await openPlanningDialog\([\s\S]*confirmLabel: "Ir a matriz"[\s\S]*if \(result\) showWorkspaceView\("matriz"\)/);
  assert.doesNotMatch(pagesIndex, /Plan Maestro de Producción — GitHub Pages \+ Google Apps Script/);
  assert.match(pagesIndex, /<option value="draft">Borrador<\/option>/);
  assert.match(pagesIndex, /function isReportSnapshotEditable\(\)/);
  assert.match(pagesIndex, /statusActions: isReportSnapshotEditable\(\)/);
  assert.match(pagesIndex, /if \(!isReportSnapshotEditable\(\)\) return escapeHtml/);
  assert.match(pagesIndex, /const mustConfirmPlanning =[^;]+\|\| commercial\.needsType \|\| commercial\.needsPlanningType;/);
  assert.match(pagesIndex, /commercialPlanningRequirement\(job, \{ alwaysPlanningType: options\.forceConfirm === true \}\)/);
  assert.match(pagesIndex, /needsPlanningType: options\.alwaysPlanningType === true \|\| !planningType/);
  assert.match(pagesIndex, /class="article-temporary-price-input"/);
  assert.match(pagesIndex, /function updateTemporaryArticlePrice\(article, value\)/);
  assert.match(pagesIndex, /\.weekly-day-table \.weekly-row--prototype td/);
  assert.match(pagesIndex, /\.weekly-day-table \.weekly-row--expedited td/);
  assert.match(pagesIndex, /function printPlanHeader\(title\)/);
  assert.match(pagesIndex, /class="individual-print-header"/);
  assert.match(pagesIndex, /class="individual-print-logo">MALDONADO/);
  assert.match(pagesIndex, /class="individual-print-code">MP CD 28-02 V02/);
  assert.match(pagesIndex, /PLAN DE PRODUCCI(?:O|Ó)N DIARIO INDIVIDUAL/);
  assert.match(pagesIndex, /PLAN DE PRODUCCI(?:O|Ó)N SEMANAL/);
  assert.match(pagesIndex, /function prepareIndividualPrint\(target\)/);
  assert.match(pagesIndex, /querySelector\("\.individual-print-date"\)/);
  assert.match(pagesIndex, /document\.body\.classList\.add\("printing-individual-plan"\)/);
  assert.match(pagesIndex, /document\.body\.classList\.remove\("printing-individual-plan"\)/);
  assert.match(pagesIndex, /grid-template-columns:\s*1fr 2fr 1fr/);
  assert.match(pagesIndex, /body\.printing-individual-plan \.report-page-table th,[\s\S]*text-align:\s*center/);
  assert.match(pagesIndex, /body\.printing-individual-plan \.executive-summary[\s\S]*display:\s*none !important/);
  assert.match(pagesIndex, /if \(!commercial\.needsType && !commercial\.needsPlanningType\) continue/);
  assert.doesNotMatch(pagesIndex, /function balanceOperators\(\)/);
  assert.match(pagesIndex, /pdfBtn\.setAttribute\("aria-busy", "true"\)/);
  assert.match(pagesIndex, /@page \{ size: A4 landscape/);
  assert.equal((pagesIndex.match(/@page \{/g) || []).length, 1);
  assert.match(pagesIndex, /id="operatorReportFutureDays"/);
  assert.match(pagesIndex, /id="adjusterReportFutureDays"/);
  assert.match(pagesIndex, /id="subcontractReportFutureDays"/);
  assert.match(pagesIndex, /id="subcontractReportStatus"/);
  assert.match(pagesIndex, /reportCoverageDiagnostics\(reportOperationsSource\(\)\)/);
  assert.match(pagesIndex, /weekPrintContext\.textContent = formatDateTime\(new Date\(\)\)/);
  assert.match(pagesIndex, /await new Promise\(\(resolve\) => window\.setTimeout\(resolve, 50\)\);\s*window\.print\(\)/);
  assert.doesNotMatch(pagesIndex, /ReportShowAll/);
  assert.match(pagesIndex, /function setGanttView\(view\)/);
  assert.match(pagesIndex, /PlanningWorkflowCore\.ganttOperationTiming/);
  assert.match(pagesIndex, /PlanningWorkflowCore\.isMachineGanttOperation\(op\)/);
  assert.match(pagesIndex, /gantt-bar--tool-change/);
  const toolChangeStyleIndex = pagesIndex.lastIndexOf(".gantt-bar.gantt-bar--tool-change {");
  assert.ok(toolChangeStyleIndex > pagesIndex.lastIndexOf(".gantt-bar.job-type-tag--urgent,"), "el fondo de cambio debe prevalecer sobre los tipos de OT");
  assert.ok(toolChangeStyleIndex > pagesIndex.lastIndexOf(".gantt-bar.risk-dot--ok,"), "el borde de cambio debe prevalecer sobre los niveles de riesgo");
  const toolChangeStyle = pagesIndex.slice(toolChangeStyleIndex, pagesIndex.indexOf("}", toolChangeStyleIndex));
  assert.match(toolChangeStyle, /repeating-linear-gradient/);
  assert.match(toolChangeStyle, /border-left-color:/);
  assert.match(pagesIndex, /Cambio de herramental/);
  assert.match(pagesIndex, /Origen:/);
  assert.match(pagesIndex, /Destino:/);
  assert.match(pagesIndex, /Maquina:/);
  assert.match(pagesIndex, /Ajustador:/);
  assert.match(pagesIndex, /Duracion:/);
  assert.match(pagesIndex, /Minutos productivos/);
  assert.match(pagesIndex, /Minutos no operativos/);
  assert.match(pagesIndex, /Causa de espera/);
  assert.match(pagesIndex, /window\.PlannerCore\?\.productionMinutes\?\.\(op\)/);
  const operationDurationSource = pagesIndex.slice(pagesIndex.indexOf("function operationDuration(op)"), pagesIndex.indexOf("const OPERATION_DURATION_CACHE"));
  assert.match(
    operationDurationSource,
    /const explicit[\s\S]*if \(explicit > 0\) return explicit;[\s\S]*if \(start && end\)/,
    "operationDuration debe preferir la duracion productiva al intervalo calendario salvo subcontratos",
  );
  assert.equal((pagesIndex.match(/aria-selected="(?:true|false)" data-view="(?:job|operator|machine|ct)"/g) || []).length, 4);
  assert.equal((pagesIndex.match(/onclick="setGanttView\('(?:job|operator|machine|ct)'\)"/g) || []).length, 4);
  assert.match(pagesIndex, /async function syncNetSuiteTwoPhase\(\)/);
  assert.match(pagesIndex, /callAppsScript\("syncNetSuiteWorkOrdersLite"\)/);
  assert.match(pagesIndex, /callAppsScript\("syncNetSuitePlanningData"\)/);
  assert.match(pagesIndex, /callAppsScript\("saveDraftSnapshot", payload\)/);
  assert.match(pagesIndex, /snapshotId: "draft"/);
  assert.match(pagesIndex, /planSnapshots\.some\(\(snapshot\) => snapshot\.snapshotId === "draft"\)/);
  assert.match(pagesIndex, /class="job-detail-operations-scroll"/);
  assert.match(pagesIndex, /id="jobToolInput"/);
  assert.match(pagesIndex, /applyToolToJob\(job\.ot, toolInput\.value\)/);
  assert.match(pagesIndex, /class="queue-tool-mini"/);
  assert.match(pagesIndex, /"Maq\/Area", "Herramental", "TC \(min\)"/);
  const detailBinding = pagesIndex.slice(pagesIndex.indexOf('const toolInput = els.selectedJobPanel.querySelector("#jobToolInput")'), pagesIndex.indexOf("function renderGantt()"));
  assert.match(detailBinding, /applyToolToJob\(job\.ot, toolInput\.value\)/, "el editor de herramental debe enlazarse dentro del detalle de OT");
  assert.match(pagesIndex, /<details class="job-resource-section/);
  assert.doesNotMatch(pagesIndex, /class="job-photo/);
  assert.doesNotMatch(pagesIndex, />Inicio NetSuite</);
  assert.doesNotMatch(pagesIndex, />Fin NetSuite</);
  assert.match(bridge, /saveDraftSnapshot: true/);
  assert.match(bridge, /restorePublishedPlanAsDraft: true/);
  assert.match(storageService, /PLAN_SNAPSHOT_PAYLOAD::/);
  assert.match(storageService, /fullState/);
  assert.match(storageService, /PLAN_SNAPSHOT_PAYLOAD::[\s\S]*getProperties\(\)/);
  assert.match(storageService, /snapshotId\.indexOf\('technical-'\) === 0/);
  assert.match(storageService, /const fullState = PP_readPlanSnapshotPayload_\(key\);[\s\S]*if \(!rows\.length && !fullState\)/);
  assert.match(storageService, /stagingKey[\s\S]*setProperties\([\s\S]*setProperty\(key, JSON\.stringify\(manifest\)\)/);
  assert.match(storageService, /catch \(error\)[\s\S]*PP_deletePlanSnapshotPayloadGeneration_/);
  assert.match(storageService, /keepPreviousPayload[\s\S]*SpreadsheetApp\.flush\(\);[\s\S]*PP_finalizePlanSnapshotPayload_/);
  assert.match(storageService, /function PP_rollbackPlanSnapshotPayload_[\s\S]*setProperty\(transaction\.key, transaction\.previousValue\)[\s\S]*PP_deletePlanSnapshotPayloadGeneration_\([^;]+transaction\.newManifest/);
  const replaceDraftSource = storageService.slice(storageService.indexOf("function PP_replaceDraftSnapshot_"), storageService.indexOf("function PP_listPlanSnapshots_"));
  assert.match(replaceDraftSource, /PP_rollbackPlanSnapshotPayload_\(payloadTransaction\.value\)/);
  assert.doesNotMatch(replaceDraftSource, /PP_storePlanSnapshotPayload_\('draft', previousPayload\)/);
  assert.match(codeService, /function restorePublishedPlanAsDraft\(snapshotId, currentPayload\)/);
  const publishingService = await readFile(path.join(result.distDir, "05-publishing-service.js"), "utf8");
  assert.match(publishingService, /PP_acquireScriptLock_\('restaurar publicado'/);
  assert.match(publishingService, /catch \(error\)[\s\S]*PP_writeState_\([\s\S]*PP_replaceDraftSnapshot_\([\s\S]*throw error/);
  assert.match(publishingService, /snapshotId: 'draft'[\s\S]*backupId: backupId[\s\S]*summary:/);
  assert.match(performanceService.replace(/\s+/g, " "), /selectedOts/);
  assert.ok((pagesIndex.match(/data-report-source-select/g) || []).length >= 3);
  assert.match(pagesIndex, /reportSnapshot = window\.PlanningWorkflowCore\.buildDraftSnapshot\(state/);
  assert.match(pagesIndex, /state\.selectedOts = Array\.isArray\(payload\.selectedOts\) \? payload\.selectedOts : \[\]/);
  assert.match(pagesIndex, /Sincronizando OTs/);
  assert.match(pagesIndex, /Sincronizando operaciones/);
  assert.match(performanceService, /selectedOts: Array\.isArray\(config\.selectedOts\) \? config\.selectedOts : \[\]/);
  assert.match(storageService, /BORRADOR_PLAN/);
});
