import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { buildProject } from "../scripts/build-appscript.mjs";

test("el build genera Apps Script y GitHub Pages", async () => {
  const result = await buildProject();
  assert.deepEqual(result.htmlFiles, ["Index.html", "IndexOperator.html", "IndexSkills.html", "Bridge.html"]);
  assert.deepEqual(result.pagesFiles, ["index.html", "operator.html", "skills.html", "manifest.webmanifest", "sw.js"]);
  const index = await readFile(path.join(result.distDir, "Index.html"), "utf8");
  const performanceService = await readFile(path.join(result.distDir, "15-performance-service.js"), "utf8");
  const storageService = await readFile(path.join(result.distDir, "02-storage.js"), "utf8");
  const bridge = await readFile(path.join(result.distDir, "Bridge.html"), "utf8");
  assert.match(index, /<title>Planeacion de Produccion<\/title>/);
  assert.match(index, /google\.script\.run/);
  assert.match(index, /PPAppsScriptBridge/);
  assert.match(index, /getAppState/);
  assert.match(index, /savePlanningStateOptimized/);
  const pagesIndex = await readFile(path.join(result.siteDir, "index.html"), "utf8");
  const serviceWorker = await readFile(path.join(result.siteDir, "sw.js"), "utf8");
  assert.match(serviceWorker, /const CACHE_NAME = "plan-maestro-[a-f0-9]{12}";/);
  assert.doesNotMatch(serviceWorker, /plan-maestro-v2\.41\.4/);
  assert.match(pagesIndex, /script\.google\.com\/macros\/s\//);
  assert.match(pagesIndex, /manifest\.webmanifest/);
  assert.match(pagesIndex, /serviceWorker\.register/);
  assert.match(pagesIndex, /PlannerCore/);
  assert.match(pagesIndex, /PlanningWorkflowCore/);
  assert.match(pagesIndex, /window\.PlanningWorkflowCore = api/);
  assert.doesNotMatch(pagesIndex, /const window = getPlanWindow\(\);[\s\S]{0,1800}window\.PlanningWorkflowCore\.isActiveGanttView/);
  assert.doesNotMatch(pagesIndex, /createPlanningWorkflowCore[\s\S]*?<\/script>\s*<script>\s*"use strict";\s*const STORAGE_KEY/);
  assert.match(pagesIndex, /scheduleCurrentPlan/);
  assert.match(pagesIndex, /NETSUITE_PLANNING_TIMEOUT_MS = 15000/);
  assert.match(pagesIndex, /PlanningWorkflowCore\.withTimeout/);
  assert.match(pagesIndex, /prepareDraftForReschedule/);
  assert.match(pagesIndex, /NetSuite no respondio; se programara con los datos ya cargados/);
  assert.match(pagesIndex, /originalEnsurePlanningDataLoaded\(showMessage, options\)/);
  assert.match(pagesIndex, /return \{ ready: hasData\(\), source: "fresh", warning: "" \}/);
  assert.match(pagesIndex, /netSuiteSyncOutcome/);
  assert.match(pagesIndex, /subcontractWindowEnd/);
  assert.match(pagesIndex, /name="ot_manual_price" type="number" min="0"/);
  assert.doesNotMatch(pagesIndex, /Piezas pendientes/);
  assert.doesNotMatch(pagesIndex, /Monto estimado/);
  assert.match(pagesIndex, /configuration\.subcontractType \|\| registeredSubcontract/);
  assert.match(pagesIndex, /configuration\.machine/);
  assert.match(pagesIndex, /function setPlanningActionsBusy/);
  assert.match(pagesIndex, /setPlanningActionsBusy\("schedule", true\)/);
  assert.match(pagesIndex, /setPlanningActionsBusy\("sync", true\)/);
  assert.doesNotMatch(pagesIndex, /id="balanceBtn"/);
  assert.doesNotMatch(pagesIndex, /els\.balanceBtn\.addEventListener/);
  assert.match(pagesIndex, /if \(isSubcontractAppOperation\(op\)\) requirement\.codes\.add\("OT_SUBCONTRACT"\)/);
  assert.match(pagesIndex, /if \(window\.PlannerCore\?\.isBendingOperation\?\.\(op\)\)[\s\S]*requirement\.codes\.add\("OT_TOOL"\)[\s\S]*requirement\.codes\.add\("OPTIONAL_KIT"\)/);
  assert.match(pagesIndex, /const result = await openPlanningDialog\([\s\S]*confirmLabel: "Ir a matriz"[\s\S]*if \(result\) showWorkspaceView\("matriz"\)/);
  assert.doesNotMatch(pagesIndex, /Plan Maestro de Producción — GitHub Pages \+ Google Apps Script/);
  assert.match(pagesIndex, /<option value="draft">Borrador<\/option>/);
  assert.match(pagesIndex, /function isReportSnapshotEditable\(\)/);
  assert.match(pagesIndex, /statusActions: isReportSnapshotEditable\(\)/);
  assert.match(pagesIndex, /if \(!isReportSnapshotEditable\(\)\) return escapeHtml/);
  assert.match(pagesIndex, /const mustConfirmPlanning =[^;]+\|\| commercial\.needsType \|\| commercial\.needsPlanningType;/);
  assert.match(pagesIndex, /commercialPlanningRequirement\(job, \{ alwaysPlanningType: options\.forceConfirm === true \}\)/);
  assert.match(pagesIndex, /needsPlanningType: options\.alwaysPlanningType === true \|\| !planningType/);
  assert.match(pagesIndex, /if \(!commercial\.needsType && !commercial\.needsPlanningType\) continue/);
  assert.doesNotMatch(pagesIndex, /function balanceOperators\(\)/);
  assert.match(pagesIndex, /pdfBtn\.setAttribute\("aria-busy", "true"\)/);
  assert.match(pagesIndex, /@page \{ size: A4 landscape/);
  assert.equal((pagesIndex.match(/@page \{/g) || []).length, 1);
  assert.match(pagesIndex, /id="operatorReportFutureDays"/);
  assert.match(pagesIndex, /id="adjusterReportFutureDays"/);
  assert.match(pagesIndex, /id="subcontractReportFutureDays"/);
  assert.match(pagesIndex, /id="subcontractReportStatus"/);
  assert.match(pagesIndex, /reportCoverageDiagnostics\(reportOperationsSource\(\)\)/);
  assert.match(pagesIndex, /weekPrintContext\.textContent = `Plan de la semana[\s\S]*Impreso/);
  assert.match(pagesIndex, /await new Promise\(\(resolve\) => window\.setTimeout\(resolve, 50\)\);\s*window\.print\(\)/);
  assert.doesNotMatch(pagesIndex, /ReportShowAll/);
  assert.match(pagesIndex, /function setGanttView\(view\)/);
  assert.equal((pagesIndex.match(/aria-selected="(?:true|false)" data-view="(?:job|operator|machine|ct)"/g) || []).length, 4);
  assert.equal((pagesIndex.match(/onclick="setGanttView\('(?:job|operator|machine|ct)'\)"/g) || []).length, 4);
  assert.match(pagesIndex, /async function syncNetSuiteTwoPhase\(\)/);
  assert.match(pagesIndex, /callAppsScript\("syncNetSuiteWorkOrdersLite"\)/);
  assert.match(pagesIndex, /callAppsScript\("syncNetSuitePlanningData"\)/);
  assert.match(pagesIndex, /callAppsScript\("saveDraftSnapshot", payload\)/);
  assert.match(pagesIndex, /snapshotId: "draft"/);
  assert.match(pagesIndex, /planSnapshots\.some\(\(snapshot\) => snapshot\.snapshotId === "draft"\)/);
  assert.match(pagesIndex, /class="job-detail-operations-scroll"/);
  assert.match(pagesIndex, /id="jobToolInput"/);
  assert.match(pagesIndex, /applyToolToJob\(job\.ot, toolInput\.value\)/);
  assert.match(pagesIndex, /class="queue-tool-mini"/);
  assert.match(pagesIndex, /"Maq\/Area", "Herramental", "TC \(min\)"/);
  const detailBinding = pagesIndex.slice(pagesIndex.indexOf('const toolInput = els.selectedJobPanel.querySelector("#jobToolInput")'), pagesIndex.indexOf("function renderGantt()"));
  assert.match(detailBinding, /applyToolToJob\(job\.ot, toolInput\.value\)/, "el editor de herramental debe enlazarse dentro del detalle de OT");
  assert.match(pagesIndex, /<details class="job-resource-section/);
  assert.doesNotMatch(pagesIndex, /class="job-photo/);
  assert.doesNotMatch(pagesIndex, />Inicio NetSuite</);
  assert.doesNotMatch(pagesIndex, />Fin NetSuite</);
  assert.match(bridge, /saveDraftSnapshot: true/);
  assert.match(performanceService.replace(/\s+/g, " "), /selectedOts/);
  assert.ok((pagesIndex.match(/data-report-source-select/g) || []).length >= 3);
  assert.match(pagesIndex, /reportSnapshot = window\.PlanningWorkflowCore\.buildDraftSnapshot\(state/);
  assert.match(pagesIndex, /state\.selectedOts = Array\.isArray\(payload\.selectedOts\) \? payload\.selectedOts : \[\]/);
  assert.match(pagesIndex, /Sincronizando OTs/);
  assert.match(pagesIndex, /Sincronizando operaciones/);
  assert.match(performanceService, /selectedOts: Array\.isArray\(config\.selectedOts\) \? config\.selectedOts : \[\]/);
  assert.match(storageService, /BORRADOR_PLAN/);
});
